"Resource/UI/HudBossHealth.res"
{
	//If you ever wanted to know how to make the border of this not tint green when merasmus is healing, this is the secret:
	//Just use a separate hud element named literally anything other than "Borderimage". No, really.
	"Background"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"Background"
		"proportionaltoparent"	"1"
		"xpos"			"cs-0.5"
		"ypos"			"11"
		"zpos"			"5"
		"wide"			"183"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"image"			"../darhud/boss_bar/boss_bar_surround"
		"scaleimage"	"1"
	}
	"Borderimage"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"Borderimage"
		"pin_to_sibling"	"Background"
		"proportionaltoparent"	"1"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"3"
		"wide"			"183"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"image"			"../darhud/boss_bar/boss_bar_surround_shadow"
		"scaleimage"	"1"
	}
	// "BackgroundShadow"
	// {
		// "controlname"	"ImagePanel"
		// "fieldname"		"BackgroundShadow"
		// "pin_to_sibling"	"Background"
		// "proportionaltoparent"	"1"
		// "xpos"			"-2"
		// "ypos"			"-2"
		// "zpos"			"3"
		// "wide"			"183"
		// "tall"			"25"
		// "autoResize"	"0"
		// "pinCorner"		"0"
		// "visible"		"1"
		// "enabled"		"1"
		// "tabPosition"	"0"
		// "image"			"../darhud/boss_bar/boss_bar_surround_shadow"
		// "scaleimage"	"1"
	// }
	
	"HealthBarPanel"
	{
		"controlname"		"EditablePanel"
		"fieldname"			"HealthBarPanel"
		"proportionaltoparent"	"1"
		"xpos"			"cs-0.5"
		"ypos"			"15"
		"zpos"			"4"
		"wide"			"168"
		"tall"			"17"
		"visible"			"1"
		"enabled"			"1"
		
		"Barimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Barimage"	
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"168"
			"tall"			"17"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"image"			"../hud/halloween_bar"
			"scaleimage"	"1"			
		}
	}				

	"StunMeter"
	{	
		"controlname"	"ContinuousProgressBar"
		"fieldname"		"StunMeter"
		"font"			"Default"
		"xpos"			"50"
		"ypos"			"10"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"0"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override"	"255 255 0 255"
		"bgcolor_override"	"50 0 0 255"
	}					
}
