"Resource/UI/HudItemEffectMeter_PowerupBottle.res"
{
	"HudItemEffectMeter"
	{
		"fieldName"		"HudItemEffectMeter"
		"xpos"			"r150"
		"xpos_minmode"	"c210"
		"ypos"			"r173"
		"ypos_minmode"	"r168"
		"zpos"			"2"
        "wide"          "75"
		"tall"			"50"
	}
	"ItemEffectMeterBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"ItemEffectMeterBG"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f2"
		"tall"			"f19"
		"image"			"../darhud/counter_neutral"
		"scaleImage"		"1"
		"teambg_0"		"../darhud/counter_neutral"
		"teambg_1"		"../darhud/counter_spectator"
		"teambg_2"		"../darhud/counter_red"
		"teambg_3"		"../darhud/counter_blue"
		"teambg_4"		"../darhud/counter_green"
		"teambg_5"		"../darhud/counter_yellow"
	}
	"BgShadow"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"BgShadow"
		"pin_to_sibling"	"ItemEffectMeterBG"
		"proportionaltoparent"	"1"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"-1"
		"wide"			"f2"
		"tall"			"f19"
		"image"			"resource/svgs/darhud/counter_mask.svg"
		"scaleImage"		"1"
		"drawcolor"		"HudShadow"
	}
	
	"ItemEffectMeterLabel"
	{
		"ControlName"				"CExLabel"
		"fieldName"				"ItemEffectMeterLabel"
		"proportionaltoparent"		"1"
		"xpos"					"0"
		"ypos"					"28"
		"ypos_minmode"			"25"
		"zpos"					"2"
		"wide"					"f0"
		"tall"					"25"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"#TF_PVE_UsePowerup_MinMode"
		"textAlignment"			"center"
		"centerwrap"				"1"
		"font"					"HudFontTiny"
		"dropshadow"				"1"
		"dropshadowoffset"		"2"
	}
	
	"ItemEffectIconBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ItemEffectIconBG"
		"xpos"			"8"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"26"
		"tall"			"26"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"resource/svgs/meters/ico_powerup_bottle.svg"
		"drawcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"ItemEffectIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ItemEffectIcon"
		"pin_to_sibling"	"ItemEffectIconBG"
		"pin_corner_to_sibling"	"pin_center_bottom"
		"pin_to_sibling_corner"	"pin_center_bottom"
		"xpos"			"0"
		"ypos"			"-5"
		"zpos"			"2"
		"wide"			"8"
		"tall"			"8"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../hud/ico_powerup_critboost_red"
		"drawcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"ItemEffectMeter"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ItemEffectMeter"
		"font"					"Default"
		"xpos"					"25"
		"ypos"					"23"
		"zpos"					"2"
		"wide"					"40"
		"tall"					"6"
		"visible"				"0"
		"enabled"				"0"
		"textAlignment"			"Left"
	}
	
	"ItemEffectMeterCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemEffectMeterCount"
		"font"			"HudFontMediumBold"
		"labelText"		"%progresscount%"
		"textAlignment" "center"
		"proportionaltoparent"	"1"
		"xpos"			"r40"
		"ypos"			"2"
		"wide"			"40"
		"tall"			"24"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
}