"Resource/UI/MvMCreditSubPanel.res"
{	
	"HeaderLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HeaderLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%header%"
		"textAlignment" "north-west"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"15"
		"fgcolor"		"GeneralLabel"
	}
	"HeaderLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HeaderLabelShadow"
		"font"			"HudFontSmallBold"
		"labelText"		"%header%"
		"textAlignment" "north-west"
		"pin_to_sibling"	"HeaderLabel"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"0"
		"wide"			"300"
		"tall"			"15"
		"fgcolor"		"GeneralShadow"
	}
		
	"TableBackground"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"TableBackground"
		"xpos"			"0"
		"ypos"			"15"
		"zpos"			"-1"
		"proportionaltoparent"	"1"
		"wide"			"f0"
		"tall"			"f15"
		"visible"		"1"
		"bgcolor_override"		"GeneralBackground"
	}
	
	"CreditRatingLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"			"CreditRatingLabel"
		"font"				"HudFontMediumBold"
		"labelText"			"%rating%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"TableBackground"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_right"
		"xpos"				"-5"
		"ypos"				"0"
		"wide"				"0"
		"tall"				"20"
		"auto_wide_tocontents"	"1"
		"fgcolor"			"GeneralLabel"
	}
	"CreditRatingLabelShadow"
	{
		"ControlName"			"CExLabel"
		"fieldName"			"CreditRatingLabelShadow"
		"font"				"HudFontMediumBold"
		"labelText"			"%ratingshadow%"
		"pin_to_sibling"		"CreditRatingLabel"
		"textAlignment"		"center"
		"xpos"				"-1"
		"ypos"				"-1"
		"zpos"				"-1"
		"wide"				"70"
		"tall"				"20"
		"auto_wide_tocontents"	"1"
		"fgcolor"			"GeneralShadow"
	}
	
	"CreditCollectedTextLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditCollectedTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Collected"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"16"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
	}
	
	"CreditCollectedCountLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditCollectedCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditscollected%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"-12"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"CreditsGreen"
	}
	"CreditCollectedCountLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditCollectedCountLabelShadow"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditscollected%"
		"textAlignment" "east"
		"pin_to_sibling"	"CreditCollectedCountLabel"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"GeneralShadow"
	}
	
	"CreditMissedTextLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditMissedTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Missed"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"28"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
	}
	
	"CreditMissedCountLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditMissedCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditsmissed%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"0"
		"xpos"			"20"
		"ypos"			"29"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"RedSolid"
	}
	"CreditMissedCountLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditMissedCountLabelShadow"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditsmissed%"
		"textAlignment" "east"
		"pin_to_sibling"	"CreditMissedCountLabel"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"GeneralShadow"
	}
	
	"CreditBonusTextLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditBonusTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Bonus"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"40"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
	}
	"CreditBonusCountLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditBonusCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditbonus%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"13"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"CreditsGreen"
	}
	"CreditBonusCountLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CreditBonusCountLabelShadow"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditbonus%"
		"textAlignment" "east"
		"pin_to_sibling"	"CreditBonusCountLabel"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"GeneralShadow"
	}
}