"Resource/UI/WaveCompletePanel.res"
{		
	"Background"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"Background"
		"xpos"			"3"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"244"
		"tall"			"80"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
	}
	
	"WaveCompleteContainer"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"WaveCompleteContainer"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"250"
		"tall"			"30"
		"visible"		"1"
		"PaintBackgroundType" "2"
		
		"Header"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"	"Header"
			"xpos"		"0"
			"ypos"		"0"
			"wide"		"250"
			"tall"		"30"
			"image"		"../darhud/square_red"
			"scaleImage"	"1"
		}
		
		"WaveCompleteLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"WaveCompleteLabel"
			"font"			"HudFontMediumSmallBold"
			"textAlignment"	"center"
			"labelText"		"%titletext%"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"250"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"GeneralLabel"		
		}
		"WaveCompleteLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"WaveCompleteLabelShadow"
			"font"			"HudFontMediumSmallBold"
			"textAlignment"	"center"
			"labelText"		"%titletext%"
			"pin_to_sibling"	"WaveCompleteLabel"
			"xpos"			"-2"
			"ypos"			"-2"
			"zpos"			"0"
			"wide"			"250"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"GeneralShadow"
		}
	}
		
	"CreditContainer"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"CreditContainer"
		"xpos"			"3"
		"ypos"			"30"
		"wide"			"150"
		"tall"			"50"
		"visible"		"1"
		
		"CreditCollectedTextLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"CreditCollectedTextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Collected"
			"textAlignment"	"west"
			"xpos"			"10"
			"ypos"			"8"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
		}
		"CreditCollectedTextLabelShadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"CreditCollectedTextLabelShadow"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Collected"
			"textAlignment"	"west"
			"pin_to_sibling"	"CreditCollectedTextLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
		
		"CreditCollectedCountLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditCollectedCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditscollected%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"8"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"CreditsGreen"
		}
		"CreditCollectedCountLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditCollectedCountLabelShadow"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditscollected%"
			"textAlignment" "east"
			"pin_to_sibling"	"CreditCollectedCountLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
		
		"CreditMissedTextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditMissedTextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Missed"
			"textAlignment" "west"
			"xpos"			"10"
			"ypos"			"20"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
		}
		"CreditMissedTextLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditMissedTextLabelShadow"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Missed"
			"textAlignment" "west"
			"pin_to_sibling"	"CreditMissedTextLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
		"CreditMissedCountLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditMissedCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditsmissed%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"20"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"RedSolid"
		}
		"CreditMissedCountLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditMissedCountLabelShadow"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditsmissed%"
			"textAlignment" "east"
			"pin_to_sibling"	"CreditMissedCountLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
		
		//the bonus label isn't there unless you qualify for it and since the drop shadow isn't there in the default hud it isn't coded to remain hidden
		//so the solution is just hide the original one and create a copy with a different name
		"CreditBonusTextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditBonusTextLabel"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"0"
		}
		"CreditBonusTextLabelCopy"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditBonusTextLabelCopy"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Bonus"
			"textAlignment" "west"
			"xpos"			"10"
			"ypos"			"32"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
		}
		"CreditBonusTextLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditBonusTextLabelShadow"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Bonus"
			"textAlignment" "west"
			"pin_to_sibling"	"CreditBonusTextLabelCopy"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
		
		"CreditBonusCountLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditBonusCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditbonus%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"32"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"CreditsGreen"
		}
		"CreditBonusCountLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"CreditBonusCountLabelShadow"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditbonus%"
			"textAlignment" "east"
			"pin_to_sibling"	"CreditBonusCountLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"GeneralShadow"
		}
	}
	
	"VerticalDivider"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"VerticalDivider"
		"xpos"			"153"
		"ypos"			"35"
		"zpos"			"-1"
		"wide"			"1"
		"tall"			"40"
		"bgcolor_override"	"255 64 64 255"
	}
	
	"RatingContainer"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"RatingContainer"
		"xpos"			"140"
		"ypos"			"30"
		"wide"			"400"
		"tall"			"400"
		"autoResize"		"1"
		"visible"		"1"
		
		
		"RatingLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RatingLabel"
			"font"			"HudFontSmall"
			"labelText"		"%ratinglabel%"
			"textAlignment" "center"
			"xpos"			"0"
			"ypos"			"5"
			"zpos"			"1"
			"wide"			"120"
			"tall"			"20"
			"fgcolor"		"GeneralLabel"
		}
		"RatingLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RatingLabelShadow"
			"font"			"HudFontSmall"
			"labelText"		"%ratinglabel%"
			"textAlignment" "center"
			"pin_to_sibling"	"RatingLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"120"
			"tall"			"20"
			"fgcolor"		"GeneralShadow"
		}
		
		"RatingTextBackground"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"	"RatingTextBackground"
			"xpos"		"45"
			"ypos"		"19"
			"wide"		"30"
			"tall"		"30"
			"zpos"		"0"
			"image"		"../darhud/achievement_red"
			"scaleImage"	"1"
		}
		"RatingText"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RatingText"
			"font"			"HudFontMediumBold"
			"labelText"		"%ratingscore%"
			"textAlignment" "center"
			"xpos"			"0"
			"ypos"			"19"
			"zpos"			"2"
			"wide"			"120"
			"tall"			"30"
			"fgcolor"		"White"
		}
		"RatingTextShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RatingTextShadow"
			"font"			"HudFontMediumBold"
			"labelText"		"%ratingscore%"
			"textAlignment" "center"
			"pin_to_sibling"	"RatingText"
			"xpos"			"-2"
			"ypos"			"-2"
			"zpos"			"1"
			"wide"			"120"
			"tall"			"30"
			"fgcolor"		"Black"
		}
	}

	"RespecBackground"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"RespecBackground"
		"xpos"			"0"
		"ypos"			"82"
		"wide"			"250"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../darhud/meter_shadow"
	}

	"RespecContainer"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"RespecContainer"
		"xpos"			"0"
		"ypos"			"80"
		"wide"			"250"
		"tall"			"20"
		"visible"		"1"
		"PaintBackgroundType" "2"
	
		"RespecTextLabelWin"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RespecTextLabelWin"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Respecs"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"3"
			"wide"			"150"
			"tall"			"20"
			"fgcolor"		"GeneralLabel"
		}
		
		"RespecCountLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RespecCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%respeccount%"
			"textAlignment" "east"
			"proportionaltoparent"	"1"
			"xpos"			"r35"
			"ypos"			"3"
			"zpos"			"1"
			"wide"			"30"
			"tall"			"20"
			"fgcolor"		"CreditsGreen"
		}
		"RespecCountLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RespecCountLabelShadow"
			"font"			"HudFontSmallBold"
			"labelText"		"%respeccount%"
			"textAlignment" "east"
			"pin_to_sibling"	"RespecCountLabel"
			"xpos"			"-1"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"30"
			"tall"			"20"
			"fgcolor"		"GeneralShadow"
		}
	}
}
